### ISSUE TITLE
incorporate browser detection into JS callback status messages

### ISSUE THREAD

**Issue by critzo** [opentechinstitute/ndt_js#1]
The updated ndt.swf file in the dt-browsercheck branch contains functions to detect the user's browser and provide appropriate error messages if the browser's flash runtime environment is not suitable to running NDT. The flash runtime of some browsers/operating systems are limited.

Incorporate browser detection error messages into the JS status messages to provide appropriate feedback to users with browsers/operating systems that have limited flash runtime envvironments.

**Comment by nkinkade** [comment]
This was fixed some time ago.
